### Cleaning Raw AI data for final dataset

In [1]:
import pandas as pd

# import seed data from CSV files
seed_data_1 = pd.read_csv(r"..\data\raw\AI\ai_seed_package_A.csv")
seed_data_2 = pd.read_csv(r"..\data\raw\AI\ai_seed_package_B.csv")

In [2]:
print(f'Seed packet A first 3\n{seed_data_1['Announced Date'].head(3)}')
print(f'Seed packet A last 3\n{seed_data_1['Announced Date'].tail(3)} \n')
print(f'Seed packet B first 3\n{seed_data_2['Announced Date'].head(3)}')
print(f'Seed packet B last 3\n{seed_data_2['Announced Date'].tail(3)}')

Seed packet A first 3
0    2016-01-01
1    2016-01-01
2    2016-01-01
Name: Announced Date, dtype: str
Seed packet A last 3
997    2022-01-01
998    2022-01-01
999    2022-01-01
Name: Announced Date, dtype: str

Seed packet B first 3
0    2024-12-19
1    2024-12-11
2    2024-12-11
Name: Announced Date, dtype: str
Seed packet B last 3
529    2022-01-01
530    2022-01-01
531    2022-01-01
Name: Announced Date, dtype: str

In [6]:
# Sorting both dataframes by "Announced Date" in ascending order
seed_data_1 = seed_data_1.sort_values(by="Announced Date", ascending=True)
seed_data_2 = seed_data_2.sort_values(by="Announced Date", ascending=True)

print(f'Seed packet A first 3\n{seed_data_1['Announced Date'].head(3)}')
print(f'Seed packet A last 3\n{seed_data_1['Announced Date'].tail(3)} \n')
print(f'Seed packet B first 3\n{seed_data_2['Announced Date'].head(3)}')
print(f'Seed packet B last 3\n{seed_data_2['Announced Date'].tail(3)}')

Seed packet A first 3
0    2016-01-01
1    2016-01-01
2    2016-01-01
Name: Announced Date, dtype: str
Seed packet A last 3
996    2022-01-01
997    2022-01-01
999    2022-01-01
Name: Announced Date, dtype: str

Seed packet B first 3
531    2022-01-01
530    2022-01-01
529    2022-01-01
Name: Announced Date, dtype: str
Seed packet B last 3
1    2024-12-11
2    2024-12-11
0    2024-12-19
Name: Announced Date, dtype: str

In [8]:
# Combine the two datasets
combined_seed_data = pd.concat([seed_data_1, seed_data_2], ignore_index=True)

print(f'Merged data first 3\n{combined_seed_data['Announced Date'].head(3)} \n')
print(f'Merged data last 3\n{combined_seed_data['Announced Date'].tail(3)}')

Merged data first 3
0    2016-01-01
1    2016-01-01
2    2016-01-01
Name: Announced Date, dtype: str

Merged data last 3
1529    2024-12-11
1530    2024-12-11
1531    2024-12-19
Name: Announced Date, dtype: str

In [9]:
combined_seed_data.to_csv(r"..\data\raw\AI\ai_seed_funding_merged.csv", index=False)

## combine series A data

In [12]:
series_a_data_1 = pd.read_csv(r"..\data\raw\AI\ai_series_A_funding_package_A.csv")
series_a_data_2 = pd.read_excel(r"..\data\raw\AI\ai_series_A_funding_package_B.xlsx")

series_a_data_1["Announced Date"] = pd.to_datetime(series_a_data_1["Announced Date"], errors='coerce')
series_a_data_2["Announced Date"] = pd.to_datetime(series_a_data_2["Announced Date"], errors='coerce')

In [13]:
print(f'Series A packet A first 3\n{series_a_data_1['Announced Date'].head(3)}')
print(f'Series A packet A last 3\n{series_a_data_1['Announced Date'].tail(3)} \n')
print(f'Series A packet B first 3\n{series_a_data_2['Announced Date'].head(3)}')
print(f'Series A packet B last 3\n{series_a_data_2['Announced Date'].tail(3)}')

Series A packet A first 3
0   2016-01-05
1   2016-01-21
2   2016-03-16
Name: Announced Date, dtype: datetime64[us]
Series A packet A last 3
465   2022-04-08
466   2022-04-11
467   2022-04-15
Name: Announced Date, dtype: datetime64[us]

Series A packet B first 3
0   2022-02-22
1   2022-02-28
2   2022-03-01
Name: Announced Date, dtype: datetime64[us]
Series A packet B last 3
212   2024-12-19
213   2024-12-21
214   2024-12-23
Name: Announced Date, dtype: datetime64[us]

In [14]:
combined_series_a_data = pd.concat([series_a_data_1, series_a_data_2], ignore_index=True)

print(f'Merged data first 3\n{combined_series_a_data['Announced Date'].head(3)} \n')
print(f'Merged data last 3\n{combined_series_a_data['Announced Date'].tail(3)}')

Merged data first 3
0   2016-01-05
1   2016-01-21
2   2016-03-16
Name: Announced Date, dtype: datetime64[us]

Merged data last 3
680   2024-12-19
681   2024-12-21
682   2024-12-23
Name: Announced Date, dtype: datetime64[us]

In [15]:
combined_series_a_data.to_csv(r"..\data\raw\AI\ai_series_A_funding_merged.csv", index=False)

# Simpled Survival dataset ready for Kaplan-Meie plots

## 0. Packages and data load

In [16]:
import pandas as pd
from datetime import datetime

# load raw data files
ai_seed = pd.read_csv(r"..\data\raw\AI\ai_seed_funding_merged.csv")
ai_series_a = pd.read_csv(r"..\data\raw\AI\ai_series_A_funding_merged.csv")

In [17]:
ai_seed.count()

Transaction Name               1532
Transaction Name URL           1532
Organization Location          1532
Organization Name              1532
Organization Name URL          1532
Funding Type                   1532
Money Raised                   1532
Money Raised Currency          1532
Money Raised (in USD)          1532
Announced Date                 1532
Diversity Spotlight             393
Number of Partner Investors     623
Number of Investors            1231
Investor Names                 1231
dtype: int64

In [18]:
ai_series_a.count()

Transaction Name               683
Transaction Name URL           468
Organization Location          683
Organization Name              683
Organization Name URL          468
Funding Type                   683
Money Raised                   683
Money Raised Currency          468
Money Raised (in USD)          468
Announced Date                 683
Diversity Spotlight            328
Number of Partner Investors    540
Number of Investors            675
Investor Names                 675
dtype: int64

In [19]:
# Make sure we're really only looking at the right round types
ai_seed = ai_seed[ai_seed["Funding Type"] == "Seed"].copy()
ai_series_a = ai_series_a[ai_series_a["Funding Type"] == "Series A"].copy()

In [20]:
ai_seed.count()

Transaction Name               1532
Transaction Name URL           1532
Organization Location          1532
Organization Name              1532
Organization Name URL          1532
Funding Type                   1532
Money Raised                   1532
Money Raised Currency          1532
Money Raised (in USD)          1532
Announced Date                 1532
Diversity Spotlight             393
Number of Partner Investors     623
Number of Investors            1231
Investor Names                 1231
dtype: int64

In [21]:
ai_series_a.count()

Transaction Name               683
Transaction Name URL           468
Organization Location          683
Organization Name              683
Organization Name URL          468
Funding Type                   683
Money Raised                   683
Money Raised Currency          468
Money Raised (in USD)          468
Announced Date                 683
Diversity Spotlight            328
Number of Partner Investors    540
Number of Investors            675
Investor Names                 675
dtype: int64

##  1.Collapse to one Seed and one Series A per startup

In [28]:
# earliest seed round per startup
ai_seed_first = (
    ai_seed.sort_values("Announced Date")
    .groupby("Organization Name", as_index=False)
    .first()
)

# earliest series A round per startup
ai_series_a_first = (
    ai_series_a.sort_values("Announced Date")
    .groupby("Organization Name", as_index=False)
    .first()
)

## 2. Merge Seed and Series A and define event/ censoring

In [29]:
# censor date: last announced date across both datasets
censor_date = max(ai_seed["Announced Date"].max(),
                   ai_series_a["Announced Date"].max())

In [31]:
# Merge: keep all seed-funded firms, attach series A info
surv = ai_seed_first.merge(
    ai_series_a_first[["Organization Name", "Announced Date"]],
    on="Organization Name",
    how="left",
    suffixes=("_seed", "_series_A")
)

surv.head(3)

,Organization Name,Transaction Name,Transaction Name URL,Organization Location,Organization Name URL,Funding Type,Money Raised,Money Raised Currency,Money Raised (in USD),Announced Date_seed,Diversity Spotlight,Number of Partner Investors,Number of Investors,Investor Names,Announced Date_series_A
0,10by10.io,Seed Round - 10by10.io,https://www.crunchbase.com/funding_round/10-by...,"San Francisco, California, United States, Nort...",https://www.crunchbase.com/organization/10-by-10,Seed,120000,USD,120000,2017-08-22,"Women Founded, Women Led",NaN,1.0,Y Combinator,NaT
1,2B0 (To Be Zero),Seed Round - 2B0 (To Be Zero),https://www.crunchbase.com/funding_round/2b0-s...,"Menlo Park, California, United States, North A...",https://www.crunchbase.com/organization/2b0,Seed,250000,USD,250000,2020-07-12,None,NaN,NaN,None,NaT
2,310.ai,Seed Round - 310.ai,https://www.crunchbase.com/funding_round/310-a...,"San Francisco, California, United States, Nort...",https://www.crunchbase.com/organization/310-ai,Seed,3700000,USD,3700000,2023-01-01,None,1.0,2.0,"AVV, Cota Capital",NaT

In [32]:
# Rename for clarity
surv = surv.rename(columns={
    "Announced Date_seed": "seed_date",
    "Announced Date_series_A": "series_a_date"
})
surv.columns

Index(['Organization Name', 'Transaction Name', 'Transaction Name URL',
       'Organization Location', 'Organization Name URL', 'Funding Type',
       'Money Raised', 'Money Raised Currency', 'Money Raised (in USD)',
       'seed_date', 'Diversity Spotlight', 'Number of Partner Investors',
       'Number of Investors', 'Investor Names', 'series_a_date'],
      dtype='object')

In [33]:
# Event indicator: 1 if series a exists, 0 otherwise
surv["event_series_a"] = surv["series_a_date"].notna().astype(int)
surv.head()

,Organization Name,Transaction Name,Transaction Name URL,Organization Location,Organization Name URL,Funding Type,Money Raised,Money Raised Currency,Money Raised (in USD),seed_date,Diversity Spotlight,Number of Partner Investors,Number of Investors,Investor Names,series_a_date,event_series_a
0,10by10.io,Seed Round - 10by10.io,https://www.crunchbase.com/funding_round/10-by...,"San Francisco, California, United States, Nort...",https://www.crunchbase.com/organization/10-by-10,Seed,120000,USD,120000,2017-08-22,"Women Founded, Women Led",NaN,1.0,Y Combinator,NaT,0
1,2B0 (To Be Zero),Seed Round - 2B0 (To Be Zero),https://www.crunchbase.com/funding_round/2b0-s...,"Menlo Park, California, United States, North A...",https://www.crunchbase.com/organization/2b0,Seed,250000,USD,250000,2020-07-12,None,NaN,NaN,None,NaT,0
2,310.ai,Seed Round - 310.ai,https://www.crunchbase.com/funding_round/310-a...,"San Francisco, California, United States, Nort...",https://www.crunchbase.com/organization/310-ai,Seed,3700000,USD,3700000,2023-01-01,None,1.0,2.0,"AVV, Cota Capital",NaT,0
3,3Analytics,Seed Round - 3Analytics,https://www.crunchbase.com/funding_round/3anal...,"Cupertino, California, United States, North Am...",https://www.crunchbase.com/organization/3analy...,Seed,474996,USD,474996,2021-02-25,None,NaN,NaN,None,NaT,0
4,3DLOOK,Seed Round - 3DLOOK,https://www.crunchbase.com/funding_round/3dloo...,"San Mateo, California, United States, North Am...",https://www.crunchbase.com/organization/3dlook,Seed,1000000,USD,1000000,2018-07-10,Women Founded,NaN,2.0,"500 Global, u.ventures",2021-03-16,1

In [34]:
# Date we stop following the firm (events or censoring)
surv["end_date"] = surv["series_a_date"].fillna(censor_date)

In [35]:
# Time to event / censor in days and months
surv["time_to_series_a_days"] = (surv["end_date"] - surv["seed_date"]).dt.days
surv["time_to_series_a_months"] = surv["time_to_series_a_days"] / 30.44

In [36]:
surv.head()

,Organization Name,Transaction Name,Transaction Name URL,Organization Location,Organization Name URL,Funding Type,Money Raised,Money Raised Currency,Money Raised (in USD),seed_date,Diversity Spotlight,Number of Partner Investors,Number of Investors,Investor Names,series_a_date,event_series_a,end_date,time_to_series_a_days,time_to_series_a_months
0,10by10.io,Seed Round - 10by10.io,https://www.crunchbase.com/funding_round/10-by...,"San Francisco, California, United States, Nort...",https://www.crunchbase.com/organization/10-by-10,Seed,120000,USD,120000,2017-08-22,"Women Founded, Women Led",NaN,1.0,Y Combinator,NaT,0,2024-12-23,2680,88.042050
1,2B0 (To Be Zero),Seed Round - 2B0 (To Be Zero),https://www.crunchbase.com/funding_round/2b0-s...,"Menlo Park, California, United States, North A...",https://www.crunchbase.com/organization/2b0,Seed,250000,USD,250000,2020-07-12,None,NaN,NaN,None,NaT,0,2024-12-23,1625,53.383706
2,310.ai,Seed Round - 310.ai,https://www.crunchbase.com/funding_round/310-a...,"San Francisco, California, United States, Nort...",https://www.crunchbase.com/organization/310-ai,Seed,3700000,USD,3700000,2023-01-01,None,1.0,2.0,"AVV, Cota Capital",NaT,0,2024-12-23,722,23.718791
3,3Analytics,Seed Round - 3Analytics,https://www.crunchbase.com/funding_round/3anal...,"Cupertino, California, United States, North Am...",https://www.crunchbase.com/organization/3analy...,Seed,474996,USD,474996,2021-02-25,None,NaN,NaN,None,NaT,0,2024-12-23,1397,45.893561
4,3DLOOK,Seed Round - 3DLOOK,https://www.crunchbase.com/funding_round/3dloo...,"San Mateo, California, United States, North Am...",https://www.crunchbase.com/organization/3dlook,Seed,1000000,USD,1000000,2018-07-10,Women Founded,NaN,2.0,"500 Global, u.ventures",2021-03-16,1,2021-03-16,980,32.194481

In [37]:
# Sanity check for no negative times
bad = surv[surv["time_to_series_a_days"] < 0]
print(len(bad))
bad.head()

0

Empty DataFrame
Columns: [Organization Name, Transaction Name, Transaction Name URL, Organization Location, Organization Name URL, Funding Type, Money Raised, Money Raised Currency, Money Raised (in USD), seed_date, Diversity Spotlight, Number of Partner Investors, Number of Investors, Investor Names, series_a_date, event_series_a, end_date, time_to_series_a_days, time_to_series_a_months]
Index: []

In [38]:
surv.count()

Organization Name              1173
Transaction Name               1173
Transaction Name URL           1173
Organization Location          1173
Organization Name URL          1173
Funding Type                   1173
Money Raised                   1173
Money Raised Currency          1173
Money Raised (in USD)          1173
seed_date                      1173
Diversity Spotlight             279
Number of Partner Investors     552
Number of Investors            1001
Investor Names                 1001
series_a_date                   409
event_series_a                 1173
end_date                       1173
time_to_series_a_days          1173
time_to_series_a_months        1173
dtype: int64

## 3 Location buckets (LA, NY, SF, Miami, Other)

### 3.1 Extarct city and state from Organziation Location

In [39]:
loc_parts = surv["Organization Location"].str.split(",", expand=True)
print(loc_parts.head())

               0            1               2               3
0  San Francisco   California   United States   North America
1     Menlo Park   California   United States   North America
2  San Francisco   California   United States   North America
3      Cupertino   California   United States   North America
4      San Mateo   California   United States   North America

In [40]:
print(len(loc_parts))

1173

In [41]:
surv["city"] = loc_parts[0].str.strip()
surv["state"] = loc_parts[1].str.strip()
print(surv.head())

  Organization Name               Transaction Name  \
0         10by10.io         Seed Round - 10by10.io
1  2B0 (To Be Zero)  Seed Round - 2B0 (To Be Zero)
2            310.ai            Seed Round - 310.ai
3        3Analytics        Seed Round - 3Analytics
4            3DLOOK            Seed Round - 3DLOOK

                                Transaction Name URL  \
0  https://www.crunchbase.com/funding_round/10-by...
1  https://www.crunchbase.com/funding_round/2b0-s...
2  https://www.crunchbase.com/funding_round/310-a...
3  https://www.crunchbase.com/funding_round/3anal...
4  https://www.crunchbase.com/funding_round/3dloo...

                               Organization Location  \
0  San Francisco, California, United States, Nort...
1  Menlo Park, California, United States, North A...
2  San Francisco, California, United States, Nort...
3  Cupertino, California, United States, North Am...
4  San Mateo, California, United States, North Am...

                               Organization Name URL Funding Type  \
0   https://www.crunchbase.com/organization/10-by-10         Seed
1        https://www.crunchbase.com/organization/2b0         Seed
2     https://www.crunchbase.com/organization/310-ai         Seed
3  https://www.crunchbase.com/organization/3analy...         Seed
4     https://www.crunchbase.com/organization/3dlook         Seed

   Money Raised Money Raised Currency  Money Raised (in USD)  seed_date  ...  \
0        120000                   USD                 120000 2017-08-22  ...
1        250000                   USD                 250000 2020-07-12  ...
2       3700000                   USD                3700000 2023-01-01  ...
3        474996                   USD                 474996 2021-02-25  ...
4       1000000                   USD                1000000 2018-07-10  ...

  Number of Partner Investors  Number of Investors          Investor Names  \
0                         NaN                  1.0            Y Combinator
1                         NaN                  NaN                    None
2                         1.0                  2.0       AVV, Cota Capital
3                         NaN                  NaN                    None
4                         NaN                  2.0  500 Global, u.ventures

  series_a_date event_series_a   end_date time_to_series_a_days  \
0           NaT              0 2024-12-23                  2680
1           NaT              0 2024-12-23                  1625
2           NaT              0 2024-12-23                   722
3           NaT              0 2024-12-23                  1397
4    2021-03-16              1 2021-03-16                   980

   time_to_series_a_months           city       state
0                88.042050  San Francisco  California
1                53.383706     Menlo Park  California
2                23.718791  San Francisco  California
3                45.893561      Cupertino  California
4                32.194481      San Mateo  California

[5 rows x 21 columns]

### 3.1 Build city_to_metro

In [42]:
ai_cities = surv[["city", "state"]].drop_duplicates().reset_index(drop=True)
ai_cities.head()

            city       state
0  San Francisco  California
1     Menlo Park  California
2      Cupertino  California
3      San Mateo  California
4       San Jose  California

In [43]:
len(ai_cities)

102

In [ ]:
ai_cities.to_csv(r"..\data\cleaned\ai_loc_map\ai_city_to_metro_template.csv", index=False)

### 3.1 Merge on both columns and enforce 1 mapping per (city, state)

In [ ]:
ai_cities_to_metro = pd.read_csv(r"..\data\cleaned\ai_loc_map\ai_city_to_metro.csv")

In [49]:
# sanity: no duplicate (city, state) pairs
dupes = ai_cities_to_metro[ai_cities_to_metro.duplicated(["city", "state"], keep=False)]
print("Duplicate (city+state in mapping:\n", dupes)

Duplicate (city+state in mapping:
 Empty DataFrame
Columns: [city, state, metro_region]
Index: []

In [50]:
# now merge
surv = surv.merge(
    ai_cities_to_metro,
    on=["city", "state"],
    how="left", 
    validate="m:1"
)

In [51]:
# Quick duplicate check on firms
dupe_firms = surv["Organization Name"].value_counts()
print(dupe_firms[dupe_firms > 1].count())

0

### 3.2 Seed amount and other Crunchbase variables

In [52]:
# Money raised at seed (USD)
surv["seed_amount_usd"] = surv["Money Raised (in USD)"]

In [54]:
# Investor counts
surv["num_partner_investors"] = surv["Number of Partner Investors"]
surv["num_investors_total"] = surv["Number of Investors"]

### 3.3 Extra Cox-friendly fields

In [55]:
surv["seed_year"] = surv["seed_date"].dt.year
surv["sector"] = "AI"  # this dataset is AI by design

In [56]:
surv.columns

Index(['Organization Name', 'Transaction Name', 'Transaction Name URL',
       'Organization Location', 'Organization Name URL', 'Funding Type',
       'Money Raised', 'Money Raised Currency', 'Money Raised (in USD)',
       'seed_date', 'Diversity Spotlight', 'Number of Partner Investors',
       'Number of Investors', 'Investor Names', 'series_a_date',
       'event_series_a', 'end_date', 'time_to_series_a_days',
       'time_to_series_a_months', 'city', 'state', 'metro_region',
       'seed_amount_usd', 'diversity_spotlight_flag', 'num_partner_investors',
       'num_investors_total', 'seed_year', 'sector'],
      dtype='object')

## 4. Final simple survival dataset

In [ ]:
simple_surv = surv[[
    "Organization Name",
    "sector",
    "seed_date",
    "series_a_date",
    "end_date",
    "time_to_series_a_months",
    "event_series_a",
    "metro_region",
    "seed_amount_usd",
    "num_partner_investors",
    "num_investors_total",
    "seed_year"
]].copy()

simple_surv = simple_surv.rename(columns={
    "Organization Name" : "firm_id"
})

simple_surv.head()

,firm_id,sector,seed_date,series_a_date,end_date,time_to_series_a_months,event_series_a,metro_region,seed_amount_usd,diversity_spotlight_flag,num_partner_investors,num_investors_total,seed_year
0,10by10.io,AI,2017-08-22,NaT,2024-12-23,88.042050,0,SFBA,120000,1,NaN,1.0,2017
1,2B0 (To Be Zero),AI,2020-07-12,NaT,2024-12-23,53.383706,0,SFBA,250000,0,NaN,NaN,2020
2,310.ai,AI,2023-01-01,NaT,2024-12-23,23.718791,0,SFBA,3700000,0,1.0,2.0,2023
3,3Analytics,AI,2021-02-25,NaT,2024-12-23,45.893561,0,SFBA,474996,0,NaN,NaN,2021
4,3DLOOK,AI,2018-07-10,2021-03-16,2021-03-16,32.194481,1,SFBA,1000000,1,NaN,2.0,2018

In [ ]:
# Save final dataset
simple_surv.to_csv(r"..\data\cleaned\cleaned_ai\ai_simple_survival.csv", index=False)